# AWS CloudFormation Template
# Corndel Level 6 AI/ML Engineer - Workshop 1
# This version introduces robust, production-aware ML pipeline concepts.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sets up a secure S3 bucket and a least-privilege IAM Role for the Corndel L6 ML Workshop 1 (WS1).'

Resources:
  # Resource 1: Secure S3 Bucket
  QuickLoanBucket:
    Type: 'AWS::S3::Bucket'
    # NEW: DeletionPolicy retains the bucket when the stack is deleted.
    # This prevents accidental data loss, a crucial real-world safety measure.
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'quickloan-ml-${AWS::Region}-${AWS::AccountId}'
      # NEW: Explicitly block all public access to the bucket.
      # This is a foundational security best practice for data storage.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # NEW: Enable versioning to keep a history of objects and prevent accidental overwrites.
      VersioningConfiguration:
        Status: Enabled

  # Resource 2: IAM Role with Least Privilege
  QuickLoanRole:
    Type: 'AWS::IAM::Role'
    Properties:
      # REMOVED: RoleName is no longer hardcoded. CloudFormation will generate a unique name.
      # This prevents collision errors if the stack is deployed multiple times.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal: { Service: 'sagemaker.amazonaws.com' }
            Action: 'sts:AssumeRole'
      Path: '/'
      # UPDATED: We now use a more restrictive set of managed policies.
      # While still broad for a workshop, this is a step towards least privilege.
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
        # REPLACED: Instead of S3 Full Access, we create our own specific policy below.
      # NEW: An inline policy that grants access ONLY to the bucket created in this stack.
      # This is a direct example of the "Principle of Least Privilege".
      Policies:
        - PolicyName: 'SageMakerS3BucketAccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                # The Resource is scoped to the specific bucket and objects within it.
                Resource:
                  - !GetAtt QuickLoanBucket.Arn
                  - !Sub '${QuickLoanBucket.Arn}/*'

Outputs:
  SageMakerRoleArn:
    Description: "The ARN of the IAM Role for SageMaker"
    Value: !GetAtt QuickLoanRole.Arn
  S3BucketName:
    Description: "The name of the S3 bucket for ML data"
    Value: !Ref QuickLoanBucket
